version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  inventory:
    build: ./inventory-service
    ports:
      - "8080:8080"

  loan:
    build: ./loan-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  notification:
    build: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq